In [2]:
# Импорт библиотеки numpy
import numpy as np


In [15]:
# Создать массив из 10 нулей
array=np.zeros(10)
print("10 nuley:")
print(array)

10 nuley:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
# Создайте массив из 10 единиц
array=np.ones(10)
print("10 edinic:")
print(array)

10 edinic:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
#Создайте массив из 10 пятерок
array=np.ones(10)*5
print("10 pyaterok:")
print(array)

10 pyaterok:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [20]:
# Создайте массив из целых чисел от 10 до 50
array=np.arange(10,51)
print("ot 10 do 50:")
print(array)


ot 10 do 50:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [21]:
# Создайте массив из чeтных чисел от 10 до 50
array=np.arange(10,51,2)
print("ot 10 do 50:")
print(array)


ot 10 do 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [23]:
# Создайте матрицу 3х3 с числами от 0 до 8
matric = np.arange(0,9).reshape(3,3)
print(matric)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
# Создать единичную матрицу 3х3
matric = np.eye(3)
print(matric)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# Используйте  Num.Py для генерации случайного числа от 0 до 1
rand = np.random.rand(1)
print("ot 0 do 1")
print(rand)


ot 0 do 1
[0.60972155]


In [11]:

# Используйте NumPY   для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения

rand = np.random.rand(25)
print("25 random")
print(rand)

25 random
[0.03141305 0.2412771  0.82868028 0.8641119  0.81029816 0.1935476
 0.89394007 0.00993178 0.02948621 0.89464765 0.62844476 0.10106485
 0.51324278 0.20124794 0.02515832 0.44668034 0.89384789 0.50191461
 0.27133526 0.11391816 0.9760605  0.32221741 0.69745823 0.05362528
 0.91265996]


In [43]:
from numpy.matrixlib import mat
# Создайте следующую матрицу используя функции библиотеки 
mat= np.arange(0.01, 1.01, 0.01).reshape(10,10)
print(mat)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [55]:
# Dана стартовая матрица(обязательно запустите код ниже в вашем решении) Эта матрица будет использоваться в последующих задачах
#Это стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [56]:
#Необходимо написать код, который вернет следующую матрицу из стартовой

print('array=', mat[2:, 1:])

array= [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [57]:
#Написать код обращения 
dv = mat[mat == 20]
print(dv)

[20]


In [59]:

#Написать код к стартовой матрице задачи1, который воспроизводит вывод, показанный ниже

print(' array= ', mat[0:3, 1].reshape(3,1))



 array=  [[ 2]
 [ 7]
 [12]]


In [61]:
#Написать код к стартовой матрице задачи1, который воспроизводит вывод, показанный ниже
print(' array= ', mat[3:])

 array=  [[16 17 18 19 20]
 [21 22 23 24 25]]


In [60]:
#Написать код к стартовой матрице задачи1, который воспроизводит вывод, показанный ниже
print(' array= ', mat[4:])

 array=  [[21 22 23 24 25]]


In [63]:
#Получить сумму всех значений в стартовой матрице 
print(mat.sum())

325


In [65]:
#Получить стандартное отклонение в стартовой матрице
print(mat.std())

7.211102550927978


In [67]:
#Получить сумму значений в колонках в стартовой матрице
print(mat.sum(axis=0))

[55 60 65 70 75]
